site_name: Skydance
site_description: A library for communication with Skydance lighting WiFi relay.
site_author: Tomas Bedrich

repo_url: https://github.com/tomasbedrich/skydance
edit_uri: https://github.com/tomasbedrich/skydance/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
